# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'o:\MCA\SEM II\DAI\Voice Assistant\UI\VoiceAssistant.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("QMainWiindow{\n"
"background-image: url(:/newPrefix/resources/VoiceAssistantUI.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setStyleSheet("background-image: url(:/newPrefix/VoiceAssistantUI.jpg);\n"
"border-style:none;")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("o:\\MCA\\SEM II\\DAI\\Voice Assistant\\UI\\../resources/VoiceAssistant2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.mainWidget.setFont(font)
        self.mainWidget.setObjectName("mainWidget")
        self.viewWidget = QtWidgets.QWidget(self.mainWidget)
        self.viewWidget.setGeometry(QtCore.QRect(630, 290, 650, 500))
        self.viewWidget.setObjectName("viewWidget")
        self.displayTextLabel = QtWidgets.QLabel(self.viewWidget)
        self.displayTextLabel.setGeometry(QtCore.QRect(75, 330, 500, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.displayTextLabel.setFont(font)
        self.displayTextLabel.setStyleSheet("color:#FFFFFF;")
        self.displayTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayTextLabel.setWordWrap(True)
        self.displayTextLabel.setObjectName("displayTextLabel")
        self.widgets = QtWidgets.QWidget(self.viewWidget)
        self.widgets.setGeometry(QtCore.QRect(170, 20, 300, 300))
        self.widgets.setObjectName("widgets")
        self.audioVisulizationWidget = QtWidgets.QWidget(self.widgets)
        self.audioVisulizationWidget.setGeometry(QtCore.QRect(-40, 0, 300, 300))
        self.audioVisulizationWidget.setObjectName("audioVisulizationWidget")
        self.lineBottom1 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineBottom1.setGeometry(QtCore.QRect(50, 150, 20, 10))
        self.lineBottom1.setStyleSheet("QFrame#lineBottom1{\n"
"background:#4885ed;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.lineBottom1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineBottom1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineBottom1.setObjectName("lineBottom1")
        self.lineBottom4 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineBottom4.setGeometry(QtCore.QRect(185, 150, 20, 10))
        self.lineBottom4.setStyleSheet("QFrame#lineBottom4 {\n"
"  background: #3cba54;\n"
"  border-bottom-left-radius: 10px;\n"
"  border-bottom-right-radius: 10px;\n"
"}")
        self.lineBottom4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineBottom4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineBottom4.setObjectName("lineBottom4")
        self.lineTop1 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineTop1.setGeometry(QtCore.QRect(50, 140, 20, 10))
        self.lineTop1.setStyleSheet("QFrame#lineTop1{\n"
"background:#4885ed;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius:10px;\n"
"}")
        self.lineTop1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineTop1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineTop1.setObjectName("lineTop1")
        self.lineTop2 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineTop2.setGeometry(QtCore.QRect(95, 140, 20, 10))
        self.lineTop2.setStyleSheet("QFrame#lineTop2 {\n"
"    background: #db3236;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"  }")
        self.lineTop2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineTop2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineTop2.setObjectName("lineTop2")
        self.lineBottom2 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineBottom2.setGeometry(QtCore.QRect(95, 150, 20, 10))
        self.lineBottom2.setStyleSheet("QFrame#lineBottom2 {\n"
"    background: #db3236;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"  }")
        self.lineBottom2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineBottom2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineBottom2.setObjectName("lineBottom2")
        self.lineTop3 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineTop3.setGeometry(QtCore.QRect(140, 140, 20, 10))
        self.lineTop3.setStyleSheet(" QFrame#lineTop3 {\n"
"    background: #f4c20d;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"  }")
        self.lineTop3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineTop3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineTop3.setObjectName("lineTop3")
        self.lineTop4 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineTop4.setGeometry(QtCore.QRect(185, 140, 20, 10))
        self.lineTop4.setStyleSheet("QFrame#lineTop4 {\n"
"  background: #3cba54;\n"
"  border-top-left-radius: 10px;\n"
"  border-top-right-radius: 10px;\n"
"}")
        self.lineTop4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineTop4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineTop4.setObjectName("lineTop4")
        self.lineBottom3 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineBottom3.setGeometry(QtCore.QRect(140, 150, 20, 10))
        self.lineBottom3.setStyleSheet("QFrame#lineBottom3 {\n"
"    background: #f4c20d;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"  }")
        self.lineBottom3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineBottom3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineBottom3.setObjectName("lineBottom3")
        self.lineTop5 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineTop5.setGeometry(QtCore.QRect(230, 140, 20, 10))
        self.lineTop5.setStyleSheet("QFrame#lineTop5{\n"
"background:#4885ed;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius:10px;\n"
"}")
        self.lineTop5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineTop5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineTop5.setObjectName("lineTop5")
        self.lineBottom5 = QtWidgets.QFrame(self.audioVisulizationWidget)
        self.lineBottom5.setGeometry(QtCore.QRect(230, 150, 20, 10))
        self.lineBottom5.setStyleSheet("QFrame#lineBottom5{\n"
"background:#4885ed;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.lineBottom5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lineBottom5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineBottom5.setObjectName("lineBottom5")
        self.resultWidget = QtWidgets.QWidget(self.widgets)
        self.resultWidget.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.resultWidget.setObjectName("resultWidget")
        self.viewLabel = QtWidgets.QLabel(self.resultWidget)
        self.viewLabel.setGeometry(QtCore.QRect(0, 0, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.viewLabel.setFont(font)
        self.viewLabel.setScaledContents(True)
        self.viewLabel.setObjectName("viewLabel")
        self.processingWidget = QtWidgets.QWidget(self.widgets)
        self.processingWidget.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.processingWidget.setObjectName("processingWidget")
        self.processingLabel = QtWidgets.QLabel(self.processingWidget)
        self.processingLabel.setGeometry(QtCore.QRect(0, 0, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.processingLabel.setFont(font)
        self.processingLabel.setScaledContents(True)
        self.processingLabel.setObjectName("processingLabel")
        self.defaultWidget = QtWidgets.QWidget(self.widgets)
        self.defaultWidget.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.defaultWidget.setObjectName("defaultWidget")
        self.defaultLabel = QtWidgets.QLabel(self.defaultWidget)
        self.defaultLabel.setGeometry(QtCore.QRect(0, 0, 300, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.defaultLabel.setFont(font)
        self.defaultLabel.setStyleSheet("color:#043886;")
        self.defaultLabel.setText("")
        self.defaultLabel.setPixmap(QtGui.QPixmap("o:\\MCA\\SEM II\\DAI\\Voice Assistant\\UI\\../resources/vv.png"))
        self.defaultLabel.setScaledContents(True)
        self.defaultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.defaultLabel.setObjectName("defaultLabel")
        self.headerWidget = QtWidgets.QWidget(self.mainWidget)
        self.headerWidget.setGeometry(QtCore.QRect(0, 0, 1200, 150))
        self.headerWidget.setObjectName("headerWidget")
        self.titleLabel = QtWidgets.QLabel(self.headerWidget)
        self.titleLabel.setGeometry(QtCore.QRect(130, 20, 800, 100))
        self.titleLabel.setStyleSheet("color: rgb(0, 0, 139);")
        self.titleLabel.setObjectName("titleLabel")
        self.logo = QtWidgets.QLabel(self.headerWidget)
        self.logo.setGeometry(QtCore.QRect(30, 30, 80, 80))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("o:\\MCA\\SEM II\\DAI\\Voice Assistant\\UI\\../resources/logo2.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.exitButton = QtWidgets.QPushButton(self.mainWidget)
        self.exitButton.setGeometry(QtCore.QRect(1870, 20, 30, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setStyleSheet("QPushButton{\n"
"background-color:red;\n"
"color: red;\n"
"cursor: pointer;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:white\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.micButtonText = QtWidgets.QLabel(self.mainWidget)
        self.micButtonText.setGeometry(QtCore.QRect(770, 915, 350, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.micButtonText.setFont(font)
        self.micButtonText.setStyleSheet("color:#ffffff")
        self.micButtonText.setObjectName("micButtonText")
        self.micButton = QtWidgets.QPushButton(self.mainWidget)
        self.micButton.setGeometry(QtCore.QRect(920, 860, 50, 50))
        self.micButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.micButton.setStyleSheet("QPushButton{\n"
"padding: 50px;\n"
"border:solid 2px;\n"
"background-color:#1976D2;\n"
"border-radius:25px;\n"
"color:#ffffff;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:#0b58d4;\n"
"\n"
"}")
        self.micButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.micButton.setIcon(icon)
        self.micButton.setIconSize(QtCore.QSize(30, 30))
        self.micButton.setCheckable(True)
        self.micButton.setAutoDefault(True)
        self.micButton.setObjectName("micButton")
        self.bottomWidget = QtWidgets.QWidget(self.mainWidget)
        self.bottomWidget.setGeometry(QtCore.QRect(-120, 980, 800, 100))
        self.bottomWidget.setStyleSheet("")
        self.bottomWidget.setObjectName("bottomWidget")
        self.layoutWidget = QtWidgets.QWidget(self.bottomWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 20, 381, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.cpu_uses = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.cpu_uses.setContentsMargins(0, 0, 0, 0)
        self.cpu_uses.setObjectName("cpu_uses")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color:white\n"
"")
        self.label_2.setObjectName("label_2")
        self.cpu_uses.addWidget(self.label_2)
        self.cpu_usesProgressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.cpu_usesProgressBar.setEnabled(True)
        self.cpu_usesProgressBar.setAutoFillBackground(False)
        self.cpu_usesProgressBar.setStyleSheet("QProgressBar{\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk \n"
"{\n"
"background-color: #22BB33;\n"
"border-radius:10px;\n"
"\n"
"}")
        self.cpu_usesProgressBar.setProperty("value", 24)
        self.cpu_usesProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_usesProgressBar.setObjectName("cpu_usesProgressBar")
        self.cpu_uses.addWidget(self.cpu_usesProgressBar)
        self.layoutWidget_2 = QtWidgets.QWidget(self.bottomWidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(140, 60, 381, 26))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.ram_uses = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.ram_uses.setContentsMargins(0, 0, 0, 0)
        self.ram_uses.setObjectName("ram_uses")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setStyleSheet("color:white\n"
"")
        self.label_4.setObjectName("label_4")
        self.ram_uses.addWidget(self.label_4)
        self.ram_usesProgressBar = QtWidgets.QProgressBar(self.layoutWidget_2)
        self.ram_usesProgressBar.setAutoFillBackground(False)
        self.ram_usesProgressBar.setStyleSheet("QProgressBar{\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk \n"
"{\n"
"background-color: #22BB33;\n"
"border-radius:10px;\n"
"\n"
"}")
        self.ram_usesProgressBar.setProperty("value", 24)
        self.ram_usesProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.ram_usesProgressBar.setObjectName("ram_usesProgressBar")
        self.ram_uses.addWidget(self.ram_usesProgressBar)
        self.Ram_2 = QtWidgets.QLabel(self.bottomWidget)
        self.Ram_2.setGeometry(QtCore.QRect(0, 0, 63, 24))
        self.Ram_2.setStyleSheet("color:white\n"
"")
        self.Ram_2.setObjectName("Ram_2")
        self.weatherWidget = QtWidgets.QWidget(self.mainWidget)
        self.weatherWidget.setGeometry(QtCore.QRect(70, 319, 441, 191))
        self.weatherWidget.setStyleSheet("")
        self.weatherWidget.setObjectName("weatherWidget")
        self.viewIcon = QtWidgets.QLabel(self.weatherWidget)
        self.viewIcon.setGeometry(QtCore.QRect(50, 10, 100, 100))
        self.viewIcon.setStyleSheet("QLabel#viewIcon{\n"
"\n"
"border-radius:20px;\n"
"\n"
"}")
        self.viewIcon.setText("")
        self.viewIcon.setPixmap(QtGui.QPixmap("o:\\MCA\\SEM II\\DAI\\Voice Assistant\\UI\\../weatherInfo/weatherIcons2/04n.png"))
        self.viewIcon.setScaledContents(True)
        self.viewIcon.setObjectName("viewIcon")
        self.temperature = QtWidgets.QLabel(self.weatherWidget)
        self.temperature.setGeometry(QtCore.QRect(190, 20, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.temperature.setFont(font)
        self.temperature.setStyleSheet("color: rgb(4, 69, 167);")
        self.temperature.setObjectName("temperature")
        self.weather = QtWidgets.QLabel(self.weatherWidget)
        self.weather.setGeometry(QtCore.QRect(50, 110, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weather.setFont(font)
        self.weather.setStyleSheet("color:#0445a7;")
        self.weather.setAlignment(QtCore.Qt.AlignCenter)
        self.weather.setObjectName("weather")
        self.city_country = QtWidgets.QLabel(self.weatherWidget)
        self.city_country.setGeometry(QtCore.QRect(160, 160, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.city_country.setFont(font)
        self.city_country.setStyleSheet("color:#FFFFFF;")
        self.city_country.setObjectName("city_country")
        self.dateTimeWidget = QtWidgets.QWidget(self.mainWidget)
        self.dateTimeWidget.setGeometry(QtCore.QRect(1410, 300, 450, 200))
        self.dateTimeWidget.setStyleSheet("/*QFrame#dateTimeFrame{\n"
"     border: 2px solid red;\n"
"    border-color: rgb(24, 205, 255);\n"
"    border-radius: 20px;\n"
"}")
        self.dateTimeWidget.setObjectName("dateTimeWidget")
        self.timeWidget = QtWidgets.QWidget(self.dateTimeWidget)
        self.timeWidget.setGeometry(QtCore.QRect(0, 0, 450, 100))
        self.timeWidget.setStyleSheet("")
        self.timeWidget.setObjectName("timeWidget")
        self.showTimeLabel = QtWidgets.QLabel(self.timeWidget)
        self.showTimeLabel.setGeometry(QtCore.QRect(30, 20, 250, 80))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.showTimeLabel.setFont(font)
        self.showTimeLabel.setStyleSheet("color:#043886;")
        self.showTimeLabel.setObjectName("showTimeLabel")
        self.am_pmTextLabel = QtWidgets.QLabel(self.timeWidget)
        self.am_pmTextLabel.setGeometry(QtCore.QRect(290, 60, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.am_pmTextLabel.setFont(font)
        self.am_pmTextLabel.setStyleSheet("color:#043886;")
        self.am_pmTextLabel.setObjectName("am_pmTextLabel")
        self.dateWidget = QtWidgets.QWidget(self.dateTimeWidget)
        self.dateWidget.setGeometry(QtCore.QRect(0, 100, 450, 100))
        self.dateWidget.setStyleSheet("")
        self.dateWidget.setObjectName("dateWidget")
        self.showDateLabel = QtWidgets.QLabel(self.dateWidget)
        self.showDateLabel.setGeometry(QtCore.QRect(30, 20, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.showDateLabel.setFont(font)
        self.showDateLabel.setStyleSheet("color:#043886;")
        self.showDateLabel.setObjectName("showDateLabel")
        self.dayNameLabel = QtWidgets.QLabel(self.dateWidget)
        self.dayNameLabel.setGeometry(QtCore.QRect(240, 40, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dayNameLabel.setFont(font)
        self.dayNameLabel.setStyleSheet("color:#043886;")
        self.dayNameLabel.setObjectName("dayNameLabel")
        self.bottomWidget_2 = QtWidgets.QWidget(self.mainWidget)
        self.bottomWidget_2.setGeometry(QtCore.QRect(1390, 980, 531, 100))
        self.bottomWidget_2.setStyleSheet("")
        self.bottomWidget_2.setObjectName("bottomWidget_2")
        self.layoutWidget_5 = QtWidgets.QWidget(self.bottomWidget_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(140, 20, 281, 26))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.Ram_Detail = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.Ram_Detail.setContentsMargins(0, 0, 0, 0)
        self.Ram_Detail.setSpacing(5)
        self.Ram_Detail.setObjectName("Ram_Detail")
        self.Ram = QtWidgets.QLabel(self.layoutWidget_5)
        self.Ram.setStyleSheet("color:white\n"
"")
        self.Ram.setObjectName("Ram")
        self.Ram_Detail.addWidget(self.Ram)
        self.RamDetail = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RamDetail.setFont(font)
        self.RamDetail.setStyleSheet("color:#FFFFFF;\n"
"")
        self.RamDetail.setObjectName("RamDetail")
        self.Ram_Detail.addWidget(self.RamDetail)
        self.Ram_Detail.setStretch(0, 1)
        self.Ram_Detail.setStretch(1, 4)
        self.layoutWidget_6 = QtWidgets.QWidget(self.bottomWidget_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(140, 60, 402, 26))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.cpu_info = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.cpu_info.setContentsMargins(0, 0, 0, 0)
        self.cpu_info.setSpacing(5)
        self.cpu_info.setObjectName("cpu_info")
        self.CPU = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CPU.setFont(font)
        self.CPU.setStyleSheet("color:white\n"
"")
        self.CPU.setObjectName("CPU")
        self.cpu_info.addWidget(self.CPU)
        self.CPU_Detail = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CPU_Detail.setFont(font)
        self.CPU_Detail.setStyleSheet("color:#FFFFFF;")
        self.CPU_Detail.setObjectName("CPU_Detail")
        self.cpu_info.addWidget(self.CPU_Detail)
        self.cpu_info.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.displayTextLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">TextLabel</span></p></body></html>"))
        self.viewLabel.setText(_translate("MainWindow", "Result Text"))
        self.processingLabel.setText(_translate("MainWindow", "<html><head/><body><p>Processing Text</p><p><br/></p></body></html>"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#0445a7;\">Voice Assistant</span></p></body></html>"))
        self.exitButton.setText(_translate("MainWindow", "X"))
        self.micButtonText.setText(_translate("MainWindow", "Click on mic Button to Start Listening"))
        self.label_2.setText(_translate("MainWindow", "CPU Uses :"))
        self.label_4.setText(_translate("MainWindow", "Ram Uses :"))
        self.Ram_2.setText(_translate("MainWindow", "CPU Uses :"))
        self.temperature.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">24 °C</span></p></body></html>"))
        self.weather.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">weather</p></body></html>"))
        self.city_country.setText(_translate("MainWindow", "City, Country"))
        self.showTimeLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#043886;\">08:45:56</span></p></body></html>"))
        self.am_pmTextLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#043886;\">PM</span></p></body></html>"))
        self.showDateLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">16-09-2021</p></body></html>"))
        self.dayNameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Sunday</span></p></body></html>"))
        self.Ram.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">RAM :</span></p></body></html>"))
        self.RamDetail.setText(_translate("MainWindow", "Ram Detail"))
        self.CPU.setText(_translate("MainWindow", "CPU :"))
        self.CPU_Detail.setText(_translate("MainWindow", "CPU Detail"))
import resourcrs_rc
